language: php

addons:
  apt:
    packages:
    - parallel

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install: make install

script:
  - make lint
  - make unitTests

cache:
  directories:
    - $HOME/.composer/cache
